# fly.toml app configuration file generated for rotasvanapi on 2023-12-27T11:26:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rotasvanapi"
primary_region = "gru"
swap_size_mb = 512

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
